[project]
name = "symclatron"
version = "0.3.1"
description = "Symbiont classifier - Machine learning-based classification of microbial symbiotic lifestyles"
authors = ["Juan C. Villada <jvillada@lbl.gov>"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[dependencies]
python = "3.12.*"
typer = "*"
pandas = "*"
numpy = "*"
hmmer = "*"
xgboost = "*"
shap = "*"
scikit-learn = "*"
tensorflow = "*"
joblib = "*"
time = "*"

[tasks]
# Setup symclatron data (run once)
setup = "./symclatron setup"

# Show symclatron information
info = "./symclatron info"

# Show help
help = "./symclatron --help"

# Run classification with default settings
classify = "./symclatron classify"

# Run quick test with provided genomes
test = "./symclatron test"

# Run test keeping temporary files
test-keep-tmp = "./symclatron test --keep-tmp"

# Advanced classification examples
classify-custom = "./symclatron classify --genome-dir data/test_genomes/ --output-dir custom_output --threads 4"
classify-verbose = "./symclatron classify --genome-dir data/test_genomes/ --output-dir verbose_output --verbose"

# Legacy tasks for backward compatibility
classify-test = "./symclatron test"
classify-test-keep-tmp = "./symclatron test --keep-tmp"
